apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: panos686/multi-client
      context: client
      docker:
        dockerfile: DockerFile.dev
      sync:
        '**/*.js': .
        '**/*.cs': .
        '**/*.html': .
    - image: panos686/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: panos686/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .

deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-server.yaml
      - k8s/client-cluster-ip-server.yaml